[package]
name = "rsdb"
version = "0.1.0"
authors = ["Devdutt Shenoi <devdutt@outlook.in>"]
edition = "2018"
description = "An experimental relational database written in rust, inspired by SQLite"

[dependencies]
